### ISSUE TITLE
Look into co-reference resolution

### ISSUE THREAD

**Issue by FullLifeGames** [Fallscout/ABSA-TensorFlow#13]
Co-Reference resolution might improve our results.

**Comment by FullLifeGames** [comment]
For the co-reference resolution I tried to look into the approach implemented in https://github.com/dasmith/stanford-corenlp-python using the Stanford CoreNLP resource.

The problem however is that this version only supports Python 2 while we're using Python 3. This would mean that it can't be included in our pipeline.

Another approach I looked into was this one which has Python 3 support: https://github.com/smilli/py-corenlp
The Stanford CoreNLP server has to be started without the Python wrapper.
Using CoreNLP that way however was really slow and doesn't finish because of "Exception in thread "pool-1-thread-3" java.lang.OutOfMemoryError: Java heap space".

Further work has to be done on this subject.

**Comment by DeastinY** [comment]
As we're doing text (json) based processing there is no issue using the official CoreNLP. You can simply spin up Python 2 for this, but make sure to include a shebang.

**Comment by FullLifeGames** [comment]
Using the CoreNLP with the Python Wrapper does work for the first few posts.
I created a method which replaces the found the references with their real meaning in a post and outputs the new post, however after around 20 posts, the program runs into a timeout.

https://github.com/Fallscout/ABSA-TensorFlow/commit/58085a37e9e2ef0190a7540b33e3c4b16758c4c1#diff-6a3409cc723a44ecf0f0059aef895a54

Example:

'Hi I bought this Barcelona sports bottle for my 5 year old son last week from your store  he s just pulled up the end with his mouth to take a drink and the whole end came completely off in his mouth! Luckily enough he spat it straight out  it s not used every day only when he s doing sport and is only a week old! Pictures in the comments'

u'Hi I bought this Barcelona sports bottle for I 5 year old son last week from your store my 5 year old son s just pulled up the end with my 5 year old son mouth to take a drink and the whole end came completely off in his mouth mouth! Luckily enough my 5 year old son spat Hi I straight out Hi I s not used every day only when my 5 year old son s doing sport and is only a week old! Pictures in the comments'

We will discuss this tomorrow.

**Comment by FullLifeGames** [comment]
The co-reference solution was applied to all of the posts and the result was saved to the following file: https://github.com/Fallscout/ABSA-TensorFlow/blob/master/stanford-corenlp-python/posts_co-referenced.json

The co-referenced posts can be found in the attribute "coref_post_message".

**Comment by FullLifeGames** [comment]
The coref posts are now tagged with OpenNLP https://github.com/Fallscout/ABSA-TensorFlow/commit/6ddc22174b9ef64a80b3f69b4f93feb13f890482
