### ISSUE TITLE
Title and abstract for the final presentation

### ISSUE THREAD

**Issue by FullLifeGames** [Fallscout/ABSA-TensorFlow#16]
For the final presentation we have to think of a title and create an abstract till Monday.

**Comment by dnerger** [comment]
Title can stay the same as before, right?

**Comment by jerryspan** [comment]
Could become more targeted towards what you are (actually) doing.

**Comment by FullLifeGames** [comment]
"Customer Experience Text Analytics for Social Media" was the current title.

We could maybe put a bit more emphasis on the "Sentiment Analysis" part with e.g. 
"Sentiment Analysis of Customer Experience for Social Media"

**Comment by dnerger** [comment]
During our meeting, we came up with the title "Sentiment Analysis for Social Media comments".

**Comment by FullLifeGames** [comment]
I created a folder for our final product (with the report) where I also put a file, where we can work on the abstract: https://github.com/Fallscout/ABSA-TensorFlow/blob/master/Final%20Product/abstract.tex

**Comment by FullLifeGames** [comment]
This is done
