### ISSUE TITLE
Finish up Visualization

### ISSUE THREAD

**Issue by DeastinY** [Fallscout/ABSA-TensorFlow#17]
Include sentiment word highlighting, bugcheck and make search more intuitive.

**Comment by dnerger** [comment]
Added sentiment word highlighting, should be no bugs anymore.

Not sure how to proceed with making search more intuitive.

**Comment by DeastinY** [comment]
https://harvesthq.github.io/chosen/
looks reasonable easy to implement and offers full search

**Comment by dnerger** [comment]
I tried to implement the search, however didn't come up with a working result.

Search can be used by typing in the product that is looked for, e.g. typing "tes" will result in Tesco, with "tesco e" resulting in Tesco Express.

Therefore, visualization is finished
