### ISSUE TITLE
Outline report

### ISSUE THREAD

**Issue by DeastinY** [Fallscout/ABSA-TensorFlow#18]
Dump some thoughts for the final report

**Comment by jerryspan** [comment]
Some advice that might help pushing the paper to a workshop/conference easier:

Keep the structure closer to a paper, i.e.
1. Introduction
2. Related Work
3. Proposed pipeline (or other title): here you describe your algorithms, pipeline, etc.
4. Experimental Setup & Results: here mention datasets (your tagged ones) and present results
5. Discussion/Conclusion (could be separate as well, given that it would be good to highlight somewhere problems that appeared during the project, e.g. language use in social media, etc.

References
Appendices: Here you can have as many as you want and mention all code requirements, visualization details, etc.
