### ISSUE TITLE
Create evaluation from manually tagged posts

### ISSUE THREAD

**Issue by DeastinY** [Fallscout/ABSA-TensorFlow#19]

**Comment by DeastinY** [comment]
If I recall correclty @Fallscout already started. @dnerger @FullLifeGames someone should finish it

**Comment by cemunds** [comment]
I have to label my own posts first. Leave it to me, just get the visualization running.

**Comment by jerryspan** [comment]
How many posts are you tagging? Are you keeping only one entity?

**Comment by DeastinY** [comment]
We have labeled 50 posts each, for 200 posts in total.
Our baseline will be a manual comparison of the sentiment for Tesco Customer Service
