### ISSUE TITLE
References in your report

### ISSUE THREAD

**Issue by jerryspan** [Fallscout/ABSA-TensorFlow#9]
I was just strolling around github (in my free time :p) and I do hope that you will add references in your report. It should be a pretty-inclusive list of the literature.

I could have a quick look tomorrow (when is ready) and provide some high-level feedback if you think it's necessary

**Comment by cemunds** [comment]
I added the references to the pdf again. Sometimes they get lost when someone whose Latex environement is not configured correctly compiles the document.

https://github.com/Fallscout/ABSA-TensorFlow/blob/master/Project%20Plan/Project%20Plan.pdf

However, normally we only list the documents and stuff that we actually used and cited. Do you actually expect a whole library of articles and papers that we just skimmed and cannot even tell if they are going to help us?

**Comment by jerryspan** [comment]
Thanks! Looks much better now.

When I meant pretty-inclusive I didn't mean to include ALL the papers you read.

However, you are doing a research project on a really-research-y topic, so I would expect a related work/literature review part where you mention existing approaches about the topic (of course with no great details) and place your research accordingly.
